### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by krzynio** [CLARIN-PL/Polem#2]
I cannot figure how to use it - I  always receive an error below.

How to properly pass strings to this function?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/WrapLem.py", line 107, in lemmatize
    return _WrapLem.CascadeLemmatizer_lemmatize(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'CascadeLemmatizer_lemmatize'.
  Possible C/C++ prototypes are:
    CascadeLemmatizer::lemmatize(UnicodeString,UnicodeString,UnicodeString,UnicodeString,std::string,bool)
    CascadeLemmatizer::lemmatize(UnicodeString,UnicodeString,UnicodeString,UnicodeString,bool)
    CascadeLemmatizer::lemmatize(UnicodeString,UnicodeString,UnicodeString,bool)

**Comment by mczuk** [comment]
Now the problem is fixed. There is a sample python script that can be run inside the Docker.
